//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ProdHouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> Budget { get; set; }
        public string Length { get; set; }
        public string Format { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public string Genre { get; set; }
        public string Status { get; set; }
    }
}
